Add support for arrays
openqasm/oqpy pull request #28
Opened 2023-03-17 00:54 UTC by anuragm

This PR adds support for native Opqy arrays. Arrays can be defined with an initial expression and can be indexed using any expression that can be converted to an AST expression. 

See added tests for example usage.

2023-03-17 00:57 UTC, anuragm commented on oqpy/classical_types.py
> +        base_type: type[_SizedVar | DurationVar | BoolVar | ComplexVar] = IntVar,
Should we try to auto-detect these quantities from `init_expression`? This can be done for most use-cases (example if the `init_expression` is a list of integers) but not all of them. For example, there is no automated way to figure out if the inputs are durations.

2023-03-17 16:46 UTC, PhilReinhold requested changes
Looking good! Thanks for putting this together, just a few ideas.

2023-03-17 16:46 UTC, PhilReinhold commented on oqpy/classical_types.py
> +        base_type: type[_SizedVar | DurationVar | BoolVar | ComplexVar] = IntVar,
I think needing it explicit sometimes and not other times is worse than just always needing it explicit.

Also should we allow specifying the type/dimensions via `__class_getiem__` a la `_SizedVar` and `ComplexVar`?

2023-03-17 16:46 UTC, PhilReinhold commented on oqpy/classical_types.py
> +class OQIndexExpression(_ClassicalVar, OQPyExpression):
Why inherit `_ClassicalVar` here? An index expression is not really a variable which needs declaration?

I guess it's an L-value, but I suppose I would just make a union type for L-values since we don't want to invoke the declaration machinery, i.e.

```python
AssignTargetTypes = _ClassicalVar | OQIndexExpression

class Program:
    def set(self, var: AssignTargetTypes, value: AstConvertible) -> Program:
        ...
```

2023-03-17 16:46 UTC, PhilReinhold commented on tests/test_directives.py
> +
We should also test assigning to an array var, i.e. `prog.set(array[idx], value)`

2023-03-20 22:23 UTC, anuragm commented on tests/test_directives.py
> +
I tested this implicitly in the loop case. I have added another explicit test as well.

2023-03-20 22:24 UTC, anuragm commented on oqpy/classical_types.py
> +        base_type: type[_SizedVar | DurationVar | BoolVar | ComplexVar] = IntVar,
Sounds good, leaving it explicit then. I have also added a `__class_getitem__` function. We can now declare arrays  in a very similar fashion to what OpenQASM advocates.

2023-03-20 22:28 UTC, anuragm commented on oqpy/classical_types.py
> +class OQIndexExpression(_ClassicalVar, OQPyExpression):
Makes sense. I have adopted this as-is.

2023-03-21 17:22 UTC, jcjaskula-aws commented on oqpy/classical_types.py
> +                size=ast.IntegerLiteral(base_type_instance.size)
According to `_SizedVar`, size should be an int and _SizedVar.__init__ should take care of the ast construction
size = base_type_instance.size

2023-03-21 17:27 UTC, jcjaskula-aws commented on oqpy/classical_types.py
> +            array_base_type = base_type_instance.type_cls(base_type=ast.FloatType())
We could reuse oqpy type: base_type=float64 or base_type=float_()

2023-03-21 17:41 UTC, jcjaskula-aws commented on oqpy/classical_types.py
> +        if isinstance(collection, ArrayVar):
Should we consider BitVar too?

2023-03-21 17:52 UTC, jcjaskula-aws commented on oqpy/classical_types.py
> +    def __getitem__(self, index: AstConvertible) -> OQIndexExpression:
What's the reason to have AstConvertible here? Should we make it more specific (i.e. int)? Would slices/tuple work right away if they implement `to_ast`?

2023-03-21 18:41 UTC, anuragm commented on oqpy/classical_types.py
> +    def __getitem__(self, index: AstConvertible) -> OQIndexExpression:
Not sure about the slices part, but keeping it `AstConvertible` means we can do something like
```
array[int, 50] values = {...}
oqpy.ForIn(program, range(49), "idx") as idx:
    program.set(values[idx+1], 99)
```
to set elements 1 to 49 to value 99.

2023-03-21 18:43 UTC, anuragm commented on oqpy/classical_types.py
> +        if isinstance(collection, ArrayVar):
BitVar implements its own slicing mechanism, and an element of `BitVar` is a `BitVar` itself. See `BitVar.__getitem__`.

2023-03-21 18:48 UTC, jcjaskula-aws commented on oqpy/classical_types.py
> +        if isinstance(collection, ArrayVar):
Arf, I see that I forgot to remove `slice` and `Iterable` there. That's ok, we will redo it in BitVar.

2023-03-21 18:51 UTC, anuragm commented on oqpy/classical_types.py
> +                size=ast.IntegerLiteral(base_type_instance.size)
Can you explain this a little bit more to me? I am not sure what the ask is. I am explaining my thought process about this code below:

The `_SizedVar.__init__()` constructor is called here on line 350, when we construct the possible `oqpy` ArrayType. Once this construction in done; in line 352, I construct an appropriate AST base type (`array_base_type`) which is then supplied later as a `type_kwargs` argument of `_ClassicalVar` (line 173) to complete the AST Array declaration.

2023-03-21 19:07 UTC, anuragm commented on oqpy/classical_types.py
> +            array_base_type = base_type_instance.type_cls(base_type=ast.FloatType())
I have updated the `ComplexVar` class so that it remembers its underlying base type, and then using that to reconstruct the correct type here.

2023-03-21 19:24 UTC, jcjaskula-aws commented on oqpy/classical_types.py
> +                size=ast.IntegerLiteral(base_type_instance.size)
Nvm, I just started testing and I understand where I was wrong. We should be able to leverage `_SizedVar.__init__(size=int)` and avoid using AST directly. But eventually, this does not bring a lot of advantages.

2023-03-21 19:39 UTC, jcjaskula-aws commented on oqpy/classical_types.py
> +            array_base_type = base_type_instance.type_cls(base_type=ast.FloatType())
Thanks. This looks good.

2023-03-21 20:21 UTC, PhilReinhold approved these changes

2023-03-21 20:52 UTC, merged