keep track of the subroutine definition order
openqasm/oqpy pull request #52
Opened 2023-07-07 23:50 UTC by jcjaskula-aws

The order of the subroutine definitions was based on their call order. We now update a list of function name at decorator call. 
Only subroutines that have been called in the program will be added to prog.subroutines. The subroutines are then added to the program at the final serialization step in order given by prog._subroutine_definition_order. 

Added a unit test.

2023-07-08 00:17 UTC, braised-babbage commented
Would it be possible to preserve the ordering of all declarations, regardless of type? For example, in OpenQASM a subroutine definition can refer to a global `const` declaration, but OpenQASM does require the `const` declaration to precede the subroutine definition. As a further extension to this mechanism, for OpenPulse we may wish to allow subroutines to refer to global definitions even if not `const`. It's also possible for a subroutine to have a gate application in its body, assuming the `defcal` precedes the subroutine definition. As it stands right now, the reordering (where subroutine definitions precede everything else) can make it hard to control the output.

2023-07-10 23:35 UTC, PhilReinhold requested changes
Looks good, just a few suggestions

2023-07-10 23:35 UTC, PhilReinhold commented on oqpy/subroutines.py
> +    if prog is not None:
Maybe raise an error if prog is None and in_place_declaration is true?

2023-07-10 23:35 UTC, PhilReinhold commented on oqpy/subroutines.py
> +        for name, subroutine_stmt in inner_prog.subroutines.items():
Probably need to make this change in `Program.__iadd__` as well. Perhaps a shared method for merging defcals/subroutines/externs?

2023-07-10 23:35 UTC, PhilReinhold commented on oqpy/program.py
> +        self, name: str, stmt: ast.SubroutineDefinition, _needs_declaration: bool = True
The method is already private, so I think the argument can just be `needs_declaration`

2023-07-10 23:35 UTC, PhilReinhold commented on oqpy/program.py
> +        self._subroutine_definition_order: list[str] = []
It wasn't clear to me that we needed this, since python dictionaries maintain insertion order. Maybe just add a comment indicating that this order is distinct from the order in `self.subroutines` when a user passes `prog` to `@subroutine` definitions

2023-07-10 23:35 UTC, PhilReinhold commented on oqpy/subroutines.py
> +    annotations: Sequence[str | tuple[str, str]] = (),
Can we add docs for these new arguments?

2023-07-11 15:22 UTC, jcjaskula-aws commented on oqpy/subroutines.py
> +        for name, subroutine_stmt in inner_prog.subroutines.items():
Made the change in `__iadd__`. Punting on adding a shared method to give it more thoughts.

2023-07-11 15:37 UTC, jcjaskula-aws commented on oqpy/program.py
> +        self._subroutine_definition_order: list[str] = []
Decided that I was asking too much to the decorator. Revamped the MR. `_subroutine_definition_order` is now called `declared_subroutines` and keep track on the already declared subroubtine (via `Program.declare`). 

The only drawback is that users cannot control the order of autodeclaring subroutines. Also, if users force the order with `Program.declare`, the subroutines will be pinned to where they are declared and autodeclared variables will be on top. We can probably implement an `add_to_header` function later if requested.

2023-07-11 17:55 UTC, PhilReinhold approved these changes

2023-07-11 17:56 UTC, PhilReinhold commented
Very nice, I like the new changes! It is much more consistent in how the declaration gets handled.

2023-07-11 18:06 UTC, merged