Qubit class supports get item
openqasm/oqpy pull request #67
Opened 2023-08-24 19:11 UTC by yitchen-tim

Related issue: https://github.com/openqasm/oqpy/issues/8

Description of change:
- Move `OQIndexExpression ` to `oqpy.base`
- Support indexing in Qubit class. `__getitem__` returns an `OQIndexExpression `

2023-08-30 15:35 UTC, yitchen-tim commented
@PhilReinhold This PR closes issue https://github.com/openqasm/oqpy/issues/8 and https://github.com/openqasm/oqpy/issues/62. Could you review and provide feedback on the implementation? Appreciated!

2023-09-05 13:57 UTC, PhilReinhold requested changes
One request, but otherwise looks good. Thanks for the contribution!

2023-09-05 13:57 UTC, PhilReinhold commented on oqpy/quantum_types.py
> +        return OQIndexExpression(collection=self, index=index, type=ast.Identifier)
I think returning an `OQIndexExpression` here is not quite correct, since `OQIndexExpression` is a subtype of `OQPyExpression` which is only for classical typed expressions. I think here you could either make a new type (e.g. `IndexedQubitArray`) or just return the `ast.IndexedExpresssion` directly.

2023-09-07 15:40 UTC, yitchen-tim commented on oqpy/quantum_types.py
> +class IndexedQubitArray:
Reason for not being a subclass of `OQPyExpression`: There is no ast type for qubits
Reason for not being a subclass of `Var`: It cannot not be declared

2023-09-07 15:41 UTC, yitchen-tim commented on oqpy/quantum_types.py
> +        return OQIndexExpression(collection=self, index=index, type=ast.Identifier)
thanks for the feedback, I updated and added a `IndexedQubitArray` class

2023-09-07 15:56 UTC, PhilReinhold approved these changes
Nice! Thanks for the changes, LGTM

2023-09-07 16:39 UTC, PhilReinhold commented on oqpy/quantum_types.py
> +        size: int = None,
```suggestion
        size: Optional[int] = None,
```

2023-09-07 16:49 UTC, PhilReinhold commented on oqpy/classical_types.py
> +    def __init__(self, collection: AstConvertible, index: AstConvertible, type: ast.ClassicalType):
```suggestion
    def __init__(self, collection: AstConvertible, index: AstConvertible, type_: ast.ClassicalType):
```

2023-09-07 16:49 UTC, PhilReinhold commented on oqpy/classical_types.py
> +        self.type = type
```suggestion
        self.type = type_
```

2023-09-07 16:52 UTC, PhilReinhold commented on oqpy/classical_types.py
> +        return OQIndexExpression(collection=self, index=index, type=self.type_cls())
```suggestion
        return OQIndexExpression(collection=self, index=index, type_=self.type_cls())
```

2023-09-07 16:52 UTC, PhilReinhold commented on oqpy/classical_types.py
> +        return OQIndexExpression(collection=self, index=index, type=self.base_type().type_cls())
```suggestion
        return OQIndexExpression(collection=self, index=index, type_=self.base_type().type_cls())
```

2023-09-07 16:56 UTC, merged

2023-09-07 17:22 UTC, jcjaskula-aws commented on oqpy/quantum_types.py
> +            size=ast.IntegerLiteral(self.size) if self.size else self.size,
```
size=ast.IntegerLiteral(self.size) if self.size else None,
```
is better