Keep the arg names in OQFunctionCall
openqasm/oqpy pull request #75
Opened 2023-09-28 20:59 UTC by jcjaskula-aws

OQFunctionCall now stores a dict of argument values indexed by the argument names. 

Waveforms can now be modified by `Program.undeclared_vars["wf_name"].args["argname"] = value` before calling `to_ast()`

2023-09-29 18:31 UTC, PhilReinhold requested changes

2023-09-29 18:31 UTC, PhilReinhold commented on oqpy/classical_types.py
> +        args: dict[str, AstConvertible],
I'm not aware of any usages that would break, but maybe just to be on the safe side, can we preserve the option to pass `args` as an iterable?

2023-09-29 21:44 UTC, jcjaskula-aws commented on oqpy/classical_types.py
> +        args: dict[str, AstConvertible],
One reason why I changed it is that `dict` are `Iterable` but would break because `map_to_ast` does not handle `dict` well. I can propose this change but I'm still in doubt if we should update map_to_ast instead.

2023-10-02 20:20 UTC, braised-babbage commented on oqpy/classical_types.py
> +        args = self.args.values() if isinstance(self.args, dict) else self.args
I think we would at least need to change the type signature for `args` when we construct `OQFunctionCall`. It currently has type `Iterable[AstConvertible]`

2023-10-02 20:40 UTC, jcjaskula-aws commented on oqpy/classical_types.py
> +        args = self.args.values() if isinstance(self.args, dict) else self.args
`dict` is technically an Iterable. Is the problem that you understand `Iterable[AstConvertible]` as `dict[AstConvertible, T]`  and we should use `Union[Iterable[AstConvertible], dict[Any, AstConvertible]]` for the type hint?

2023-10-03 16:34 UTC, PhilReinhold commented on oqpy/classical_types.py
> +        args = self.args.values() if isinstance(self.args, dict) else self.args
Yeah, I think the correct type hint is `Union[Iterable[AstConvertible], dict[Any, AstConvertible]]`

2023-10-03 18:16 UTC, merged